using SelfMX.Api.Authentication;
using Xunit;

namespace SelfMX.Api.Tests.Authentication;

/// <summary>
/// Tests for SHA-512 crypt verification.
/// Test hashes generated with: openssl passwd -6 -salt [salt] "[password]"
/// </summary>
public class Sha512CryptVerifierTests
{
    // Hash generated by: openssl passwd -6 -salt testsalt123 "testpassword"
    private const string TestPassword = "testpassword";
    private const string TestSalt = "testsalt123";
    private const string TestHash = "$6$testsalt123$8.ZsCdnu4PWB.8.yvt3rXoZBYF91LOlzF2UmfsaNnK6I1JGdKmhAKrCbboCngN.7U7mcxtYhNl2IJWmbe.IXA/";

    [Fact]
    public void Verify_CorrectPassword_ReturnsTrue()
    {
        // Act
        var result = Sha512CryptVerifier.Verify(TestPassword, TestHash);

        // Assert
        Assert.True(result, $"Password '{TestPassword}' should match hash");
    }

    [Fact]
    public void Verify_WrongPassword_ReturnsFalse()
    {
        // Act
        var result = Sha512CryptVerifier.Verify("wrongpassword", TestHash);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void Verify_EmptyPassword_ReturnsFalse()
    {
        // Act
        var result = Sha512CryptVerifier.Verify("", TestHash);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void Verify_NullPassword_ReturnsFalse()
    {
        // Act
        var result = Sha512CryptVerifier.Verify(null!, TestHash);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void Verify_EmptyHash_ReturnsFalse()
    {
        // Act
        var result = Sha512CryptVerifier.Verify(TestPassword, "");

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void Verify_NullHash_ReturnsFalse()
    {
        // Act
        var result = Sha512CryptVerifier.Verify(TestPassword, null!);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void Verify_InvalidHashFormat_ReturnsFalse()
    {
        // Act
        var result = Sha512CryptVerifier.Verify(TestPassword, "not-a-valid-hash");

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void Verify_Sha256Hash_ReturnsFalse()
    {
        // SHA-256 hash format ($5$) should not be accepted
        var sha256Hash = "$5$salt$hash";

        // Act
        var result = Sha512CryptVerifier.Verify(TestPassword, sha256Hash);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void ComputeForDebug_ReturnsMatchingHash()
    {
        // Act
        var computed = Sha512CryptVerifier.ComputeForDebug(TestPassword, TestHash);

        // Assert
        Assert.Equal(TestHash, computed);
    }

    // Additional test with different salt/password
    // Hash generated by: openssl passwd -6 -salt abcdef "MyPassword123"
    [Fact]
    public void Verify_DifferentSaltAndPassword_Works()
    {
        const string password = "MyPassword123";
        const string hash = "$6$abcdef$uc26VHwLwC6GncULJb3W.lRMkLArBme9h21EppAvtfkz8xXTegEhr7Zlyv3Ryo3fOIJstsRVmA6N.N1rb.iJW0";

        // Act
        var result = Sha512CryptVerifier.Verify(password, hash);

        // Assert
        Assert.True(result);
    }
}
