import type { DnsRecord } from './schemas';

/**
 * Convert a full DNS record name to a relative name for the zone file.
 * For example:
 * - "abc._domainkey.example.com" with domain "example.com" -> "abc._domainkey"
 * - "example.com" with domain "example.com" -> "@"
 * - "_dmarc.example.com" with domain "example.com" -> "_dmarc"
 */
function toRelativeName(fullName: string, domain: string): string {
  // Normalize: remove any trailing dots
  const normalizedName = fullName.replace(/\.+$/, '');
  const normalizedDomain = domain.replace(/\.+$/, '');

  // If name equals domain exactly, it's the apex
  if (normalizedName === normalizedDomain) {
    return '@';
  }

  // If name ends with .domain, strip it
  const suffix = `.${normalizedDomain}`;
  if (normalizedName.endsWith(suffix)) {
    return normalizedName.slice(0, -suffix.length);
  }

  // Otherwise return as-is (shouldn't happen with valid data)
  return normalizedName;
}

/**
 * Generate a BIND zone file from DNS records
 */
export function generateBindFile(domain: string, records: DnsRecord[]): string {
  const lines = [
    `; DNS Records for ${domain}`,
    `; Generated by SelfMX`,
    `; Import this file in your DNS provider`,
    '',
    `$ORIGIN ${domain}.`,
    '$TTL 3600',
    '',
  ];

  for (const record of records) {
    // Convert full name to relative name for BIND format
    const name = toRelativeName(record.name, domain);
    // BIND format: name TTL class type value
    // CNAME values need trailing dot for FQDNs
    const value = record.type === 'CNAME' ? `${record.value}.` : record.value;
    lines.push(`${name}\tIN\t${record.type}\t${value}`);
  }

  return lines.join('\n');
}

/**
 * Download a BIND zone file
 */
export function downloadBindFile(domain: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${domain}-dns-records.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
