import type { DnsRecord } from './schemas';

/**
 * Generate a BIND zone file from DNS records
 */
export function generateBindFile(domain: string, records: DnsRecord[]): string {
  const lines = [
    `; DNS Records for ${domain}`,
    `; Generated by SelfMX`,
    `; Import this file in your DNS provider`,
    '',
    `$ORIGIN ${domain}.`,
    '$TTL 3600',
    '',
  ];

  for (const record of records) {
    // BIND format: name TTL class type value
    // CNAME values need trailing dot for FQDNs
    const value = record.type === 'CNAME' ? `${record.value}.` : record.value;
    lines.push(`${record.name}\tIN\t${record.type}\t${value}`);
  }

  return lines.join('\n');
}

/**
 * Download a BIND zone file
 */
export function downloadBindFile(domain: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${domain}-dns-records.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
