using System.Security.Cryptography;
using System.Text;
using CryptSharp;

namespace SelfMX.Api.Authentication;

/// <summary>
/// Verifies SHA-512 crypt hashes in the format $6$salt$hash.
/// Compatible with hashes generated by: openssl passwd -6 "password"
/// Uses CryptSharp library for cross-platform compatibility.
/// </summary>
public static class Sha512CryptVerifier
{
    private const string Sha512Prefix = "$6$";

    /// <summary>
    /// Verifies a password against a SHA-512 crypt hash.
    /// </summary>
    public static bool Verify(string password, string hash)
    {
        if (string.IsNullOrEmpty(password) || string.IsNullOrEmpty(hash))
            return false;

        if (!hash.StartsWith(Sha512Prefix))
            return false;

        try
        {
            // CryptSharp.Crypter.CheckPassword returns true if password matches hash
            return Crypter.CheckPassword(password, hash);
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Debug method to compute and return the hash for comparison.
    /// </summary>
    public static string ComputeForDebug(string password, string existingHash)
    {
        try
        {
            // Extract salt from existing hash and compute new hash
            return Crypter.Sha512.Crypt(password, existingHash);
        }
        catch (Exception ex)
        {
            return $"ERROR: {ex.Message}";
        }
    }
}
